// CI-only API doubles and ephemeral browser accounts. No production API or database is touched.
const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.MORA_QA_BASE_URL || 'http://127.0.0.1:5173';
const uid = '00000000-0000-4000-8000-000000000001';
const profile = { id:uid, username:'qa_only', display_name:'Browser QA', bio:'Isolated browser verification', roles:['Writer'], profile_visibility:'public', account_status:'active', platform_role:'user', onboarding_completed:true, external_links:{}, avatar_path:uid+'/qa.png', cover_path:uid+'/qa.png' };
const claims = {sub:uid,exp:Math.floor(Date.now()/1000)+3600,aal:'aal1',role:'authenticated'};
const token = Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify(claims)).toString('base64url')+'.qa';
const session = {access_token:token,refresh_token:'qa-only',token_type:'bearer',expires_in:3600,expires_at:claims.exp,user:{id:uid,aud:'authenticated',role:'authenticated',email:'qa@tests.invalid',app_metadata:{},user_metadata:{},created_at:new Date().toISOString()}};
const report = { checks:[], errors:[], network:[] };
let qaPage, qaBrowser;
const output = process.env.MORA_QA_OUTPUT || 'test-results/browser';
fs.mkdirSync(output,{recursive:true});
(async () => {
 const browser = await chromium.launch({headless:true,args:['--no-sandbox']});
 qaBrowser=browser;
 const ctx = await browser.newContext({viewport:{width:1440,height:900}});
 await ctx.route('https://mora-tests.supabase.co/**', async route => {
  const req=route.request(), url=new URL(req.url());
  report.network.push(req.method()+' '+url.pathname);
  const headers={'access-control-allow-origin':'*','access-control-allow-headers':'*','content-type':'application/json','content-range':'0-0/0'};
  let body=[];
  if(req.method()==='OPTIONS') return route.fulfill({status:204,headers});
  if(url.pathname.includes('/storage/v1/')) return route.fulfill({status:200,contentType:'image/svg+xml',body:'<svg xmlns="http://www.w3.org/2000/svg" width="300" height="100"><rect width="300" height="100" fill="#5765a0"/></svg>'});
  if(url.pathname==='/rest/v1/profiles') body=[profile];
  if(url.pathname==='/rest/v1/rpc/mora_capabilities') body={version:3,project_workspace:false,polls:false};
  if(url.pathname==='/auth/v1/user') body=session.user;
  if(url.pathname==='/auth/v1/logout') body={};
  return route.fulfill({status:200,headers,body:JSON.stringify(body)});
 });
 await ctx.addInitScript(({session})=>{localStorage.setItem('sb-mora-tests-auth-token',JSON.stringify(session));if(!localStorage.getItem('mora-language')) localStorage.setItem('mora-language','vi');if(!localStorage.getItem('mora-theme')) localStorage.setItem('mora-theme','light')},{session});
 const page=await ctx.newPage();qaPage=page;
 page.on('pageerror',e=>report.errors.push(e.message));
 const check=(s)=>{report.checks.push(s);console.log('PASS '+s)};
 await page.goto(base+'/studio/projects');
 await page.getByLabel('Tên dự án').fill('QA autosave');
 await page.getByRole('button',{name:'Tạo dự án',exact:true}).click();
 await page.getByRole('heading',{name:'QA autosave',level:1}).waitFor();
 const draftUrl=page.url();
 assert.match(draftUrl,/local-/);
 assert.equal(await page.getByRole('button',{name:'Đồng bộ để cộng tác'}).count(),0);
 check('local-first creation and missing-backend capability gate');
 await page.getByRole('navigation',{name:'Mục trong dự án'}).getByRole('button',{name:'Lore truyện',exact:true}).click();
 await page.getByRole('button',{name:'Thêm mục',exact:true}).click();
 await page.getByLabel('Tiêu đề',{exact:true}).fill('QA lore');
 await page.getByLabel('Nội dung',{exact:true}).fill('Immediate navigation must preserve this text.');
 await page.getByRole('link',{name:'Dự án của tôi',exact:true}).click();
 await page.locator('.local-project-poster').getByRole('link').filter({hasText:'QA autosave'}).click();
 await page.getByRole('navigation',{name:'Mục trong dự án'}).getByRole('button',{name:'Lore truyện',exact:true}).click();
 const restored=await page.evaluate(async()=>{const m=await import('/src/lib/localProjects.js');return m.listLocalProjects()});
 assert.equal(restored.find(item=>draftUrl.endsWith(item.id)).sections[0].content.text,'Immediate navigation must preserve this text.');
 assert.equal(await page.getByLabel('Nội dung',{exact:true}).inputValue(),'Immediate navigation must preserve this text.');
 check('autosave survives immediate in-app navigation');
 await page.getByRole('navigation',{name:'Mục trong dự án'}).getByRole('button',{name:'Nhân vật',exact:true}).click();
 await page.locator('.character-gallery').getByRole('button',{name:'Thêm nhân vật',exact:true}).click();
 await page.getByRole('button',{name:'Danh sách nhân vật',exact:true}).click();
 await page.locator('.character-poster').click();
 await page.getByLabel('Tên',{exact:true}).fill('QA character');
 await page.getByLabel('Mục tiêu',{exact:true}).fill('Test persistence');
 const feature=await page.locator('.character-feature').boundingBox();
 assert(Math.abs(feature.width/feature.height-16/9)<.06);
 await page.getByRole('button',{name:'Danh sách nhân vật',exact:true}).click();
 await page.getByRole('button',{name:'Sơ đồ quan hệ',exact:true}).click();
 await page.locator('.canvas-toolbar').getByRole('button',{name:'Thêm nhân vật',exact:true}).click();
 await page.getByLabel('Tên',{exact:true}).fill('QA second');
 const first=page.locator('.canvas-node').first();
 const second=page.locator('.canvas-node').nth(1);
 await first.getByRole('button',{name:'Tạo liên kết'}).click();
 await page.getByPlaceholder('Loại quan hệ').fill('QA link');
 await second.getByRole('button',{name:'Tạo liên kết'}).click();
 assert.equal(await page.getByLabel('Loại quan hệ',{exact:true}).inputValue(),'QA link');
 const point=await first.boundingBox();
 await page.mouse.move(point.x+40,point.y+40);await page.mouse.down();await page.mouse.move(point.x+100,point.y+85,{steps:5});await page.mouse.up();
 const after=await first.boundingBox();assert(after.x>point.x+40);
 await page.getByRole('button',{name:'Phóng to',exact:true}).click();
 check('16:9 character detail, relation connection, drag and zoom');
 await page.getByRole('link',{name:'Dự án của tôi',exact:true}).click();
 await page.locator('.local-project-poster').getByRole('link').filter({hasText:'QA autosave'}).click();
 await page.getByRole('navigation',{name:'Mục trong dự án'}).getByRole('button',{name:'Nhân vật',exact:true}).click();
 assert.equal(await page.locator('.character-poster').count(),2);
 check('characters persist after leaving editor');
 await page.goto(base+'/profile');
 await page.getByRole('heading',{name:'Browser QA',level:1}).waitFor();
 const avatar=await page.locator('.profile-main .avatar').boundingBox();assert(Math.abs(avatar.width-avatar.height)<2);
 check('profile avatar keeps square aspect ratio');
 await page.screenshot({path:output+'/profile-light.png'});
 for(const theme of ['light','dark']) {
  await page.evaluate(t=>localStorage.setItem('mora-theme',t),theme);
  await page.reload();await page.getByRole('heading',{name:'Browser QA',level:1}).waitFor();
  assert.equal(await page.locator('html').getAttribute('data-theme'),theme);
  await page.setViewportSize({width:390,height:844});
  for(const path of ['/profile','/studio/projects','/projects','/friends','/feed','/learn','/settings','/notifications']) {
   await page.goto(base+path);await page.waitForTimeout(200);
   const width=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,view:innerWidth}));
   assert(width.scroll<=width.view+2,`${theme} ${path} overflow ${width.scroll}/${width.view}`);
  }
  await page.goto(base+'/profile');await page.getByRole('heading',{name:'Browser QA',level:1}).waitFor();
  await page.screenshot({path:output+'/profile-'+theme+'-mobile.png'});
  check(theme+' mobile navigation and no document overflow on 8 routes');
 }
 assert.deepEqual(report.errors,[]);
 check('no uncaught browser errors');
 await browser.close();fs.writeFileSync(output+'/report.json',JSON.stringify(report,null,2));
})().catch(async e=>{if(qaPage){await qaPage.screenshot({path:output+'/failure.png',fullPage:true}).catch(()=>{});fs.writeFileSync(output+'/failure.html',await qaPage.content().catch(()=>''));}if(qaBrowser)await qaBrowser.close();fs.writeFileSync(output+'/report.json',JSON.stringify({...report,failure:e.message},null,2));console.error(e);process.exit(1)});
