import { useEffect, useState } from 'react'
import { AudioLines, BookOpen, BriefcaseBusiness, Globe2, Image as ImageIcon, Link2, MessageCircle } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useAuth } from '../context/AuthContext'

const sampleComments = [
  { by:'Mottopa · đội ngũ Morimori (minh họa)', text:'Mottopa và đội ngũ sáng tạo chân thành cảm ơn các đóng góp từ bạn nhé! Nếu yêu thích chương trình cộng tác viên sáng tạo Morimori thì hãy đăng ký ở bài ghim đầu trang. Đội ngũ rất thích đề xuất của bạn.' },
]

export default function DemoPage() {
  const { profile } = useAuth()
  const [choice,setChoice] = useState('')
  const [perspective,setPerspective] = useState('creator')
  const [audio,setAudio] = useState(null)
  const [audioUrl,setAudioUrl] = useState('')
  const [reply,setReply] = useState('')
  const [comments,setComments] = useState(sampleComments)
  useEffect(() => { if (!audio) return undefined; const url = URL.createObjectURL(audio); setAudioUrl(url); return () => URL.revokeObjectURL(url) },[audio])
  return <div className="content-page demo-page"><header className="glass-card demo-banner"><strong>DEMO · NỘI DUNG HƯ CẤU · NOT REAL USER DATA</strong><h1>Thế giới, Dự án và Feed kết nối ra sao?</h1><p>Toàn bộ Morimori, Mottopa, khóa học và các bài bên dưới chỉ là mô phỏng trên trang này. Không có nội dung nào được thêm vào tài khoản hoặc cơ sở dữ liệu của bạn.</p><Link className="secondary-button" to="/feed">← Về Feed thật</Link></header>
    <div className="demo-roles"><section className="glass-card"><Globe2 /><span>01 · WORLD / THẾ GIỚI</span><h2>Morimori · bối cảnh sáng tạo</h2><p>Nơi lưu trữ lore, nhân vật Heo con, vùng đất, mối quan hệ và dòng thời gian. Có thể giữ riêng tư ngay cả khi bạn chưa công bố dự án.</p><small>Trong sản phẩm thật: vào Thế giới để quản lý dữ liệu worldbuilding của chính bạn.</small></section>
      <section className="glass-card"><BriefcaseBusiness /><span>02 · PROJECT / DỰ ÁN</span><h2>Morimori · trò chơi (minh họa)</h2><p>Hồ sơ giới thiệu trò chơi với mục tiêu, tiến độ, thành viên, phần chọn công khai và lời mời cộng tác. Tác giả giả định: Mottopa.</p><small>Chỉ hồ sơ được chủ dự án chủ động xuất bản mới xuất hiện trong Khám phá dự án.</small></section>
      <section className="glass-card"><MessageCircle /><span>03 · FEED / BÀI VIẾT</span><h2>Thảo luận gắn với Morimori</h2><p>Ảnh, video, âm thanh, bình chọn và nhận xét là bài đăng độc lập. Người đăng có thể chọn liên kết tới dự án Morimori đã công khai.</p><small>Liên kết giúp đội dự án xem đóng góp theo dự án; đăng Feed không tự tạo hay công bố dự án.</small></section></div>
    <section className="glass-card demo-course"><BookOpen /><div><strong>KHÓA HỌC CỦA BẠN · BẢN DEMO, CHƯA ĐĂNG</strong><h2>Thiết kế nhân vật từ ý tưởng đến hồ sơ</h2><p>Ví dụ khóa học cá nhân của {profile?.display_name || 'bạn'}: phác thảo ý tưởng, xây động cơ và kết nối nhân vật với dự án. Miễn phí; khi đăng thật cần quyền Course Creator và duyệt khóa học.</p><span>Chương minh họa: Ý tưởng → Hồ sơ nhân vật → Phản biện & hoàn thiện</span></div></section>
    <div className="section-title"><h2>Ba bài viết cá nhân · ví dụ minh họa</h2><p>Nội dung không xuất hiện trên Feed thật hoặc trong hồ sơ của bạn.</p></div>
    <div className="demo-posts"><article className="glass-card"><span className="demo-chip">1 / 3 · DISCUSSION · THẢO LUẬN</span><h3>{profile?.display_name || 'Bạn'} (mô phỏng)</h3><p>Mình đang thử xây dựng một nhân vật dễ thương nhưng vẫn có mục tiêu và điểm yếu rõ ràng. Theo mọi người, điều gì làm một nhân vật khiến mình muốn theo dõi lâu dài?</p><div className="demo-post-footer"><MessageCircle size={16} /> #character-design · Có thể nhận bình luận trong Feed thật</div></article>
      <article className="glass-card"><span className="demo-chip">2 / 3 · POLL · BÌNH CHỌN</span><h3>{profile?.display_name || 'Bạn'} (mô phỏng)</h3><p>Bạn muốn xem nội dung nào tiếp theo trong quá trình phát triển một nhân vật?</p><div className="demo-vote">{['Bản phác thảo đầu tiên','Câu chuyện phía sau nhân vật','Thử nghiệm giọng thoại'].map((option) => <button key={option} className={choice === option ? 'selected' : ''} onClick={() => setChoice(option)} aria-pressed={choice === option}>{option}</button>)}</div><small>{choice ? `Bạn đã chọn “${choice}” trên trang demo. Lựa chọn này không gửi lên Mora.` : 'Nhấn để thử bình chọn trên trang demo.'}</small></article>
      <article className="glass-card"><span className="demo-chip">3 / 3 · AUDIO · LIÊN KẾT DỰ ÁN</span><h3>{profile?.display_name || 'Bạn'} (mô phỏng)</h3><div className="demo-perspectives"><button className={perspective === 'creator' ? 'selected' : ''} onClick={() => setPerspective('creator')}>Góc nhìn người sáng tạo</button><button className={perspective === 'audience' ? 'selected' : ''} onClick={() => setPerspective('audience')}>Góc nhìn khán giả</button></div><p>{perspective === 'creator' ? 'Đây là đoạn voice mình dự kiến sẽ đưa vào nhân vật Heo con trong Morimori, các bạn thấy sao?' : 'Mình gợi ý nhà sáng tạo Mottopa đưa đoạn voice này vào cho Heo con nhé, hiện tại mình thấy chưa hay lắm.'}</p><span className="linked-project"><Link2 size={16} /> Liên kết: Morimori · dự án công khai giả định</span><label className="demo-upload"><AudioLines size={17} /> {audio ? `Nghe bản thử: ${audio.name}` : 'Chọn tệp âm thanh của bạn để thử tại chỗ'}<input type="file" accept="audio/mpeg,audio/wav,audio/ogg,audio/webm,audio/mp4" onChange={(event) => { const file = event.target.files?.[0]; if (file?.type.startsWith('audio/') && file.size < 40 * 1024 * 1024) setAudio(file) }} hidden /></label>{audioUrl ? <audio className="post-audio" src={audioUrl} controls /> : <p className="demo-note">Không có bản thu thật được cung cấp; ví dụ không tự tạo giọng nói hay tải tệp lên máy chủ.</p>}
        <div className="demo-comment"><strong>Bình luận của Mottopa · minh họa</strong><p>{comments[0].text}</p>{comments.slice(1).map((item,index) => <p key={index}><strong>{item.by}:</strong> {item.text}</p>)}<form onSubmit={(event) => { event.preventDefault(); if (!reply.trim()) return; setComments([...comments,{ by:`${profile?.display_name || 'Bạn'} · bản demo`,text:reply.trim() }]); setReply('') }}><input value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Viết bình luận thử, chỉ hiển thị tại đây…" maxLength={2000} /><button className="secondary-button" disabled={!reply.trim()}>Gửi trong demo</button></form></div></article></div>
    <section className="glass-card demo-outro"><ImageIcon /><p>Để đăng nội dung thật, quay lại Feed. Ảnh được hỗ trợ trên site hiện tại; video, âm thanh và bình chọn cần migration Supabase trước khi dùng được. Dự án chỉ được liên kết khi công khai.</p><Link className="primary-button" to="/feed">Mở Feed thật</Link></section>
  </div>
}
