import { ArrowUpRight, Coins, Link2, Plus, Trash2 } from 'lucide-react'
import { Link } from 'react-router-dom'
import { budgetTotal, gameEntries, matchesToEarn, positiveAmount } from '../lib/gameEconomy'
import { isGameProject } from '../lib/projectWorkflows'

const labels = { currency: 'Tiền tệ', item: 'Vật phẩm', series: 'Dòng skin', skin: 'Skin', event: 'Sự kiện' }
const types = { currency: 'game_currency', item: 'game_item', series: 'skin_series', skin: 'game_skin', event: 'game_event' }
const money = (amount) => new Intl.NumberFormat('vi-VN').format(positiveAmount(amount))

function Input({ label, value, onChange, disabled, multiline = false, ...props }) {
  return <label className="game-field">{label}{multiline ? <textarea value={value || ''} onChange={(event) => onChange(event.target.value)} disabled={disabled} {...props} /> : <input value={value || ''} onChange={(event) => onChange(event.target.value)} disabled={disabled} {...props} />}</label>
}

function Select({ label, value, onChange, options, disabled, empty = 'Chưa chọn' }) {
  return <label className="game-field">{label}<select value={value || ''} disabled={disabled} onChange={(event) => onChange(event.target.value)}><option value="">{empty}</option>{options.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select></label>
}

export default function GameDesignPanel({ tab, draft, onChange, canEdit, localProjects = [], ownerId }) {
  const isEventProject = draft.project_type === 'Game Event'
  const parent = isEventProject ? localProjects.find((project) => project.id === draft.parent_project_id && project.owner_id === ownerId && isGameProject(project.project_type) && project.project_type !== 'Game Event') : null
  const ownedHeroes = draft.nodes.filter((node) => node.canvas_kind === 'character')
  const parentHeroes = parent?.nodes.filter((node) => node.canvas_kind === 'character' && draft.allowed_hero_ids?.includes(node.id)) || []
  const heroes = [...ownedHeroes, ...parentHeroes]
  const ownCurrencies = gameEntries(draft.sections, types.currency)
  const parentCurrencies = (parent ? gameEntries(parent.sections, types.currency).filter((currency) => draft.allowed_currency_ids?.includes(currency.id)) : [])
  const currencies = [...ownCurrencies, ...parentCurrencies]
  const items = gameEntries(draft.sections, types.item)
  const series = gameEntries(draft.sections, types.series)
  const skins = gameEntries(draft.sections, types.skin)
  const events = gameEntries(draft.sections, types.event)
  const childEvents = !isEventProject ? localProjects.filter((project) => project.owner_id === ownerId && project.parent_project_id === draft.id && project.project_type === 'Game Event') : []
  const childEventSummary = childEvents.map((child) => {
    const childSkins = gameEntries(child.sections, types.skin)
    const childSeries = gameEntries(child.sections, types.series)
    const localCurrencies = gameEntries(child.sections, types.currency)
    return <article className="game-child-project" key={child.id}>
      <Link className="game-child-link" to={`/studio/projects/${child.id}`}><strong>{child.name}</strong><ArrowUpRight size={15} /></Link>
      <p>{child.allowed_hero_ids?.length || 0} tướng được chọn · {childSeries.length} dòng skin · {childSkins.length} skin · dự toán {money(budgetTotal(childSkins))} VND</p>
      {childSeries.map((line) => <div className="game-child-series" key={line.id}><strong>{line.title}</strong><span>{childSkins.filter((skin) => skin.content.series_id === line.id).length} skin</span>{line.content.text && <p>{line.content.text}</p>}</div>)}
      {childSkins.map((skin) => {
        const hero = draft.nodes.find((node) => node.id === skin.content.hero_id) || child.nodes.find((node) => node.id === skin.content.hero_id)
        const currency = [...ownCurrencies, ...localCurrencies].find((item) => item.id === skin.content.currency_id)
        return <p className="game-child-skin" key={skin.id}><strong>{skin.title}</strong> · {hero?.title || 'chưa gắn tướng'} · {skin.content.price === undefined || !currency ? 'chưa đặt giá trong game' : `${money(skin.content.price)} ${currency.content.symbol || currency.title}`} · dự toán {money(skin.content.productionCost)} VND</p>
      })}
    </article>
  })

  function add(kind) {
    if (!canEdit) return
    onChange({ sections: [...draft.sections, { id: crypto.randomUUID(), section_type: 'custom', title: `${labels[kind]} mới`, sort_order: draft.sections.length, content: { category: types[kind], text: '' } }] })
  }
  function patch(id, patch) {
    if (!canEdit) return
    onChange({ sections: draft.sections.map((section) => section.id === id ? { ...section, ...patch, content: patch.content ? { ...section.content, ...patch.content } : section.content } : section) })
  }
  function field(entry, name, value) { patch(entry.id, { content: { [name]: value } }) }
  function remove(id) { if (canEdit && window.confirm('Xóa mục này khỏi dự án?')) onChange({ sections: draft.sections.filter((section) => section.id !== id) }) }
  const common = (entry) => <Input key={`${entry.id}-title`} label="Tên" value={entry.title} disabled={!canEdit} onChange={(value) => patch(entry.id, { title: value })} maxLength={160} />
  const rm = (entry) => <button type="button" className="text-danger" disabled={!canEdit} onClick={() => remove(entry.id)}><Trash2 size={14} /> Xóa</button>

  const sourcePicker = isEventProject && <section className="game-source glass-card"><h3><Link2 size={17} /> Kết nối game gốc</h3><p>Một dự án sự kiện có thể tham chiếu tướng và tiền tệ từ game của bạn trên thiết bị này. Chọn đúng tài nguyên cần dùng; đây chưa phải lời mời truy cập cho tài khoản khác.</p><Select label="Dự án game gốc" value={draft.parent_project_id} disabled={!canEdit} options={localProjects.filter((project) => project.owner_id === ownerId && isGameProject(project.project_type) && project.project_type !== 'Game Event' && project.id !== draft.id).map((project) => ({ id: project.id, title: project.name }))} onChange={(id) => onChange({ parent_project_id: id || null, allowed_hero_ids: [], allowed_currency_ids: [] })} empty="Chưa chọn game gốc" />{parent && <><h4>Chọn tướng được đưa vào sự kiện</h4><div className="game-access-picks">{parent.nodes.filter((node) => node.canvas_kind === 'character').map((node) => <label key={node.id}><input type="checkbox" disabled={!canEdit} checked={draft.allowed_hero_ids?.includes(node.id) || false} onChange={(event) => onChange({ allowed_hero_ids: event.target.checked ? [...(draft.allowed_hero_ids || []), node.id] : (draft.allowed_hero_ids || []).filter((id) => id !== node.id) })} />{node.title}</label>)}</div><h4>Chọn tiền tệ được dùng</h4><div className="game-access-picks">{gameEntries(parent.sections, types.currency).map((currency) => <label key={currency.id}><input type="checkbox" disabled={!canEdit} checked={draft.allowed_currency_ids?.includes(currency.id) || false} onChange={(event) => onChange({ allowed_currency_ids: event.target.checked ? [...(draft.allowed_currency_ids || []), currency.id] : (draft.allowed_currency_ids || []).filter((id) => id !== currency.id) })} />{currency.title}</label>)}</div></>}</section>

  const addButton = (kind) => <button type="button" className="primary-button small" disabled={!canEdit} onClick={() => add(kind)}><Plus size={15} /> Thêm {labels[kind].toLowerCase()}</button>
  const empty = (message) => <p className="inline-empty">{message}</p>

  return <div className="game-design-page">
    {sourcePicker}
    {tab === 'currency' && <section className="game-design-panel glass-card"><header><div><span className="eyebrow purple">KINH TẾ TRONG GAME</span><h2>Tiền tệ</h2><p>Đặt cách kiếm và cách tiêu từng loại tiền. Mỗi giá được tính trong một đơn vị riêng, không tự quy đổi giữa các loại tiền.</p></div>{addButton('currency')}</header>{!ownCurrencies.length && empty('Thêm loại tiền đầu tiên để đặt giá vật phẩm và skin.')}{ownCurrencies.map((entry) => <article className="game-entity" key={entry.id}>{common(entry)}<div className="game-field-row"><Input label="Ký hiệu" value={entry.content.symbol} disabled={!canEdit} onChange={(value) => field(entry, 'symbol', value)} maxLength={20} /><Input label="Kiếm được mỗi trận (nếu có)" type="number" min="0" step="1" value={entry.content.earned_per_match} disabled={!canEdit} onChange={(value) => field(entry, 'earned_per_match', value)} /></div><Input label="Cách nhận và mục đích sử dụng" multiline value={entry.content.text} disabled={!canEdit} onChange={(value) => field(entry, 'text', value)} />{rm(entry)}</article>)}{parentCurrencies.length > 0 && <p className="game-source-note">{parentCurrencies.length} loại tiền tệ được tham chiếu từ game gốc · chỉ chỉnh sửa ở dự án chủ.</p>}</section>}
    {tab === 'items' && <section className="game-design-panel glass-card"><header><div><span className="eyebrow purple">DANH MỤC TRONG GAME</span><h2>Vật phẩm</h2><p>Lưu công dụng, giá và loại tiền. Nhân vật có thể được ghi trong mô tả hoặc liên kết qua sơ đồ quan hệ.</p></div>{addButton('item')}</header>{!items.length && empty('Chưa có vật phẩm nào.')}{items.map((entry) => <article className="game-entity" key={entry.id}>{common(entry)}<div className="game-field-row"><Select label="Đơn vị thanh toán" value={entry.content.currency_id} disabled={!canEdit} options={currencies} onChange={(value) => field(entry, 'currency_id', value)} /><Input label="Giá trong game" type="number" min="0" step="1" value={entry.content.price} disabled={!canEdit} onChange={(value) => field(entry, 'price', value)} /></div><Input label="Công dụng / hiệu ứng" value={entry.content.effect} disabled={!canEdit} multiline onChange={(value) => field(entry, 'effect', value)} /><Input label="Câu chuyện / điều kiện mở khóa" value={entry.content.text} disabled={!canEdit} multiline onChange={(value) => field(entry, 'text', value)} />{rm(entry)}</article>)}</section>}
    {tab === 'skins' && <section className="game-design-panel glass-card"><header><div><span className="eyebrow purple">BỘ SƯU TẬP</span><h2>Dòng skin</h2><p>Tạo câu chuyện cho một series, gắn skin với tướng, tiền tệ và chi phí sản xuất. Số skin được tính từ những skin bạn thêm.</p></div>{addButton('series')}</header>{!series.length && empty('Bắt đầu bằng một dòng skin, rồi thêm các skin vào dòng đó.')}{series.map((entry) => <article className="game-entity" key={entry.id}>{common(entry)}<strong>{skins.filter((skin) => skin.content.series_id === entry.id).length} skin trong dòng</strong><Input label="Câu chuyện chung" value={entry.content.text} disabled={!canEdit} multiline onChange={(value) => field(entry, 'text', value)} /><Select label="Thuộc sự kiện (nếu có)" value={entry.content.event_id} disabled={!canEdit} options={events} onChange={(value) => field(entry, 'event_id', value)} />{rm(entry)}</article>)}<div className="game-subheading"><h3>Danh sách skin</h3>{addButton('skin')}</div>{skins.map((entry) => <article className="game-entity" key={entry.id}>{common(entry)}<div className="game-field-row"><Select label="Dòng skin" value={entry.content.series_id} disabled={!canEdit} options={series} onChange={(value) => field(entry, 'series_id', value)} /><Select label="Tướng" value={entry.content.hero_id} disabled={!canEdit} options={heroes} onChange={(value) => field(entry, 'hero_id', value)} /></div><Input label="Câu chuyện của skin" value={entry.content.text} disabled={!canEdit} multiline onChange={(value) => field(entry, 'text', value)} /><div className="game-field-row"><Select label="Tiền tệ của người chơi" value={entry.content.currency_id} disabled={!canEdit} options={currencies} onChange={(value) => field(entry, 'currency_id', value)} /><Input label="Giá skin trong game" type="number" min="0" step="1" value={entry.content.price} disabled={!canEdit} onChange={(value) => field(entry, 'price', value)} /><Input label="Chi phí sản xuất dự kiến (VND)" type="number" min="0" step="1" value={entry.content.productionCost} disabled={!canEdit} onChange={(value) => field(entry, 'productionCost', value)} /></div>{rm(entry)}</article>)}</section>}
    {tab === 'game_events' && <section className="game-design-panel glass-card"><header><div><span className="eyebrow purple">DÒNG SỰ KIỆN</span><h2>Sự kiện game</h2><p>Gắn các tướng tham gia, diễn biến và dòng skin. Một dự án sự kiện riêng có thể tham chiếu game gốc trên cùng thiết bị.</p></div>{addButton('event')}</header>{!events.length && empty('Chưa có sự kiện nào.')}{events.map((entry) => { const eventSeries = series.filter((line) => line.content.event_id === entry.id); const eventSkins = skins.filter((skin) => eventSeries.some((line) => line.id === skin.content.series_id)); return <article className="game-entity" key={entry.id}>{common(entry)}<Input label="Cốt truyện và mốc diễn biến" value={entry.content.text} disabled={!canEdit} multiline onChange={(value) => field(entry, 'text', value)} /><h4>Tướng tham gia ({entry.content.hero_ids?.length || 0})</h4><div className="game-access-picks">{heroes.map((hero) => <label key={hero.id}><input type="checkbox" disabled={!canEdit} checked={entry.content.hero_ids?.includes(hero.id) || false} onChange={(event) => field(entry, 'hero_ids', event.target.checked ? [...(entry.content.hero_ids || []), hero.id] : (entry.content.hero_ids || []).filter((id) => id !== hero.id))} />{hero.title}</label>)}</div><p>{eventSeries.length} dòng skin · {eventSkins.length} skin · chi phí sản xuất dự kiến {money(budgetTotal(eventSkins))} VND</p>{rm(entry)}</article> })}</section>}
    {tab === 'economy' && <section className="game-design-panel glass-card"><header><div><span className="eyebrow purple">LIÊN KẾT & CÂN BẰNG</span><h2>Quan hệ và tính toán</h2><p>Quan hệ nhân vật được vẽ ở mục Nhân vật. Bảng dưới cho thấy cần bao nhiêu trận để mua vật phẩm hoặc skin khi đã đặt mức nhận tiền mỗi trận.</p></div></header><div className="game-entity"><h3>Quan hệ nhân vật</h3>{draft.links.filter((link) => link.canvas_kind === 'character').length ? draft.links.filter((link) => link.canvas_kind === 'character').map((edge) => <p key={edge.id}>{draft.nodes.find((node) => node.id === edge.source_id)?.title} ↔ {draft.nodes.find((node) => node.id === edge.target_id)?.title}: {edge.label || 'Chưa đặt tên quan hệ'}</p>) : empty('Chưa có đường nối nhân vật. Mở mục Nhân vật để tạo mối quan hệ.')}</div><div className="game-entity"><h3>Chi phí cho người chơi</h3>{[...items, ...skins].filter((entry) => entry.content.currency_id).map((entry) => { const currency = currencies.find((item) => item.id === entry.content.currency_id); const matches = matchesToEarn(entry.content.price, currency?.content.earned_per_match); return <p key={entry.id}><strong>{entry.title}</strong> · {money(entry.content.price)} {currency?.content.symbol || currency?.title || 'đơn vị'} · {matches === null ? 'chưa đặt lượng nhận mỗi trận' : `khoảng ${matches} trận`}</p> })}{!items.length && !skins.length && empty('Thêm vật phẩm hoặc skin để xem chi phí.')}</div><div className="game-entity"><h3>Chi phí sản xuất dòng skin</h3>{series.map((line) => <p key={line.id}><strong>{line.title}</strong> · {skins.filter((skin) => skin.content.series_id === line.id).length} skin · {money(budgetTotal(skins.filter((skin) => skin.content.series_id === line.id)))} VND</p>)}{!series.length && empty('Tạo dòng skin để theo dõi số lượng và dự toán.')}</div>{childEvents.length > 0 && <div className="game-entity"><h3>Sự kiện đang liên kết với game này</h3>{childEventSummary}</div>}</section>}
    {isEventProject && !parent && <p className="game-source-note"><Coins size={15} /> Chọn game gốc cùng tài khoản trên thiết bị này để dùng tướng và tiền tệ. Mời cộng tác viên khác cần đồng bộ dự án và phân quyền trên máy chủ.</p>}
  </div>
}
