import { Circle, Link2, Plus, Type, WholeWord } from 'lucide-react'

export function ProjectWorkspaceNav({ title, tabs, labels, active, onSelect, footer }) {
  return <aside className="project-space-sidebar glass-card"><div className="project-space-sidebar-heading"><small>KHÔNG GIAN DỰ ÁN</small><h2>{title}</h2></div><nav aria-label="Mục trong dự án">{tabs.map((key) => <button type="button" className={key === active ? 'active' : ''} aria-current={key === active ? 'page' : undefined} key={key} onClick={() => onSelect(key)}>{labels[key] || key}</button>)}</nav>{footer && <div className="project-space-sidebar-footer">{footer}</div>}</aside>
}

export function ProjectEditorToolbar({ label, character, land, board, textSize, onSize, onCommand, canEdit }) {
  return <div className="project-editor-toolbar glass-card" role="toolbar" aria-label={`Công cụ ${label}`}><span className="project-editor-toolbar-label">{label}</span><div className="project-editor-toolbar-tools"><button type="button" disabled={!canEdit || (!board && !character && !land)} onClick={() => onCommand(board ? 'text' : 'add')}><Type size={16} /> {character ? 'Thêm nhân vật' : land ? 'Thêm vùng đất' : 'Thêm chữ'}</button><label>Cỡ chữ<select value={textSize} onChange={(event) => onSize(Number(event.target.value))} disabled={!canEdit || !board} aria-label="Cỡ chữ trên bảng">{[14,16,20,24,32].map((size) => <option key={size} value={size}>{size}px</option>)}</select></label><button type="button" disabled={!canEdit || !board} onClick={() => onCommand('box')} title={board ? 'Thêm ô văn bản' : 'Dùng trong mục Tổng quan hoặc Lore'}><WholeWord size={17} /> Ô văn bản</button><button type="button" disabled={!canEdit || !board} onClick={() => onCommand('circle')} title={board ? 'Thêm khung tròn' : 'Dùng trong mục Tổng quan hoặc Lore'}><Circle size={16} /> Khung tròn</button><button type="button" disabled={!canEdit || (!board && !character && !land)} onClick={() => onCommand('connect')}><Link2 size={16} /> Nối</button><button type="button" className="project-toolbar-more" disabled={!canEdit || (!board && !character && !land)} onClick={() => onCommand(board ? 'box' : 'add')} aria-label="Thêm nội dung"><Plus size={16} /></button></div></div>
}
