import { createContext, useContext, useEffect, useMemo, useState } from 'react'

export const interfaceLanguages = [
  ['en','English'], ['vi','Tiếng Việt'], ['es','Español'], ['fr','Français'], ['de','Deutsch'],
  ['pt','Português'], ['ja','日本語'], ['ko','한국어'], ['zh','简体中文'], ['th','ภาษาไทย'], ['id','Bahasa Indonesia'],
]

const translations = {
  en: { feed:'Feed', friends:'Connections', worlds:'Worlds', projects:'Explore projects', learn:'Learn', profile:'Profile', studio:'My workspace', search:'Search creators and projects', messages:'Messages', notifications:'Notifications', signout:'Sign out', settings:'Settings', theme:'Appearance', light:'Light', dark:'Dark', system:'Device setting', language:'Interface language', demo:'Explore a guided example', welcome:'Choose your language', welcomeHint:'English is the default. Change this any time in Settings.', continue:'Continue', compose:'What are you creating?', publish:'Publish', publishing:'Publishing…', image:'Image', video:'Video', audio:'Audio', poll:'Poll', discussion:'Discussion', topic:'Topic', linkedProject:'Public project', noProject:'No linked project', forYou:'For you', latest:'Latest', welcomeBack:'Welcome', feedIntro:'Share your process and explore the creative community.', rights:'Creative principles', rightsText:'You own your work. AI is a tool and never decides canon.', feedEmpty:'The feed is waiting for its first story', feedEmptyDesc:'Public posts from the community will appear here.' },
  vi: { feed:'Bảng tin', friends:'Kết nối', worlds:'Thế giới', projects:'Khám phá dự án', learn:'Học tập', profile:'Hồ sơ', studio:'Không gian của tôi', search:'Tìm người sáng tạo và dự án', messages:'Tin nhắn', notifications:'Thông báo', signout:'Đăng xuất', settings:'Cài đặt', theme:'Giao diện', light:'Sáng', dark:'Tối', system:'Theo thiết bị', language:'Ngôn ngữ giao diện', demo:'Xem ví dụ minh họa', welcome:'Chọn ngôn ngữ của bạn', welcomeHint:'Mặc định là tiếng Anh. Có thể đổi bất kỳ lúc nào trong Cài đặt.', continue:'Tiếp tục', compose:'Bạn đang sáng tạo điều gì?', publish:'Đăng bài', publishing:'Đang đăng…', image:'Hình ảnh', video:'Video', audio:'Âm thanh', poll:'Bình chọn', discussion:'Thảo luận', topic:'Chủ đề', linkedProject:'Dự án công khai', noProject:'Không liên kết dự án', forYou:'Dành cho bạn', latest:'Mới nhất', welcomeBack:'Xin chào', feedIntro:'Chia sẻ quá trình sáng tạo và khám phá cộng đồng.', rights:'Nguyên tắc sáng tạo', rightsText:'Bạn sở hữu nội dung của mình. AI chỉ hỗ trợ và không tự quyết định canon.', feedEmpty:'Bảng tin đang chờ câu chuyện đầu tiên', feedEmptyDesc:'Bài viết công khai từ cộng đồng sẽ xuất hiện tại đây.' },
  es: { feed:'Inicio', friends:'Conexiones', worlds:'Mundos', projects:'Explorar proyectos', learn:'Aprender', profile:'Perfil', studio:'Mi espacio', search:'Buscar creadores y proyectos', messages:'Mensajes', notifications:'Notificaciones', signout:'Salir', settings:'Configuración', theme:'Apariencia', light:'Claro', dark:'Oscuro', system:'Sistema', language:'Idioma', demo:'Ver ejemplo', welcome:'Elige tu idioma', continue:'Continuar', compose:'¿Qué estás creando?', publish:'Publicar', image:'Imagen', video:'Video', audio:'Audio', poll:'Encuesta', discussion:'Debate', topic:'Tema', linkedProject:'Proyecto público' },
  fr: { feed:'Fil', friends:'Connexions', worlds:'Mondes', projects:'Explorer les projets', learn:'Apprendre', profile:'Profil', studio:'Mon espace', search:'Rechercher des créateurs et projets', messages:'Messages', notifications:'Notifications', signout:'Déconnexion', settings:'Paramètres', theme:'Apparence', light:'Clair', dark:'Sombre', system:'Système', language:'Langue', demo:'Voir un exemple', welcome:'Choisissez votre langue', continue:'Continuer', compose:'Que créez-vous ?', publish:'Publier', image:'Image', video:'Vidéo', audio:'Audio', poll:'Sondage', discussion:'Discussion', topic:'Sujet', linkedProject:'Projet public' },
  de: { feed:'Feed', friends:'Kontakte', worlds:'Welten', projects:'Projekte entdecken', learn:'Lernen', profile:'Profil', studio:'Mein Arbeitsbereich', search:'Kreative und Projekte suchen', messages:'Nachrichten', notifications:'Mitteilungen', signout:'Abmelden', settings:'Einstellungen', theme:'Darstellung', light:'Hell', dark:'Dunkel', system:'System', language:'Sprache', demo:'Beispiel ansehen', welcome:'Sprache wählen', continue:'Weiter', compose:'Woran arbeitest du?', publish:'Veröffentlichen', image:'Bild', video:'Video', audio:'Audio', poll:'Umfrage', discussion:'Diskussion', topic:'Thema', linkedProject:'Öffentliches Projekt' },
  pt: { feed:'Feed', friends:'Conexões', worlds:'Mundos', projects:'Explorar projetos', learn:'Aprender', profile:'Perfil', studio:'Meu espaço', search:'Buscar criadores e projetos', messages:'Mensagens', notifications:'Notificações', signout:'Sair', settings:'Configurações', theme:'Aparência', light:'Claro', dark:'Escuro', system:'Sistema', language:'Idioma', demo:'Ver exemplo', welcome:'Escolha seu idioma', continue:'Continuar', compose:'O que você está criando?', publish:'Publicar', image:'Imagem', video:'Vídeo', audio:'Áudio', poll:'Enquete', discussion:'Discussão', topic:'Tema', linkedProject:'Projeto público' },
  ja: { feed:'フィード', friends:'つながり', worlds:'世界', projects:'プロジェクトを探す', learn:'学ぶ', profile:'プロフィール', studio:'マイスペース', search:'クリエイターとプロジェクトを検索', messages:'メッセージ', notifications:'通知', signout:'ログアウト', settings:'設定', theme:'外観', light:'ライト', dark:'ダーク', system:'端末に合わせる', language:'言語', demo:'使用例を見る', welcome:'言語を選択', continue:'続ける', compose:'何を制作していますか？', publish:'投稿', image:'画像', video:'動画', audio:'音声', poll:'投票', discussion:'議論', topic:'トピック', linkedProject:'公開プロジェクト' },
  ko: { feed:'피드', friends:'연결', worlds:'세계', projects:'프로젝트 탐색', learn:'학습', profile:'프로필', studio:'내 작업 공간', search:'창작자와 프로젝트 검색', messages:'메시지', notifications:'알림', signout:'로그아웃', settings:'설정', theme:'화면', light:'라이트', dark:'다크', system:'기기 설정', language:'언어', demo:'예시 보기', welcome:'언어 선택', continue:'계속', compose:'무엇을 만들고 있나요?', publish:'게시', image:'이미지', video:'동영상', audio:'오디오', poll:'투표', discussion:'토론', topic:'주제', linkedProject:'공개 프로젝트' },
  zh: { feed:'动态', friends:'联系', worlds:'世界', projects:'探索项目', learn:'学习', profile:'个人资料', studio:'我的工作区', search:'搜索创作者和项目', messages:'消息', notifications:'通知', signout:'退出登录', settings:'设置', theme:'外观', light:'浅色', dark:'深色', system:'跟随系统', language:'语言', demo:'查看示例', welcome:'选择语言', continue:'继续', compose:'你在创作什么？', publish:'发布', image:'图片', video:'视频', audio:'音频', poll:'投票', discussion:'讨论', topic:'话题', linkedProject:'公开项目' },
  th: { feed:'ฟีด', friends:'เครือข่าย', worlds:'โลก', projects:'สำรวจโปรเจกต์', learn:'เรียนรู้', profile:'โปรไฟล์', studio:'พื้นที่ของฉัน', search:'ค้นหาผู้สร้างและโปรเจกต์', messages:'ข้อความ', notifications:'การแจ้งเตือน', signout:'ออกจากระบบ', settings:'ตั้งค่า', theme:'ธีม', light:'สว่าง', dark:'มืด', system:'ตามอุปกรณ์', language:'ภาษา', demo:'ดูตัวอย่าง', welcome:'เลือกภาษา', continue:'ดำเนินการต่อ', compose:'คุณกำลังสร้างอะไร?', publish:'โพสต์', image:'รูปภาพ', video:'วิดีโอ', audio:'เสียง', poll:'โหวต', discussion:'อภิปราย', topic:'หัวข้อ', linkedProject:'โปรเจกต์สาธารณะ' },
  id: { feed:'Beranda', friends:'Koneksi', worlds:'Dunia', projects:'Jelajahi proyek', learn:'Belajar', profile:'Profil', studio:'Ruang saya', search:'Cari kreator dan proyek', messages:'Pesan', notifications:'Notifikasi', signout:'Keluar', settings:'Pengaturan', theme:'Tampilan', light:'Terang', dark:'Gelap', system:'Sistem', language:'Bahasa', demo:'Lihat contoh', welcome:'Pilih bahasa', continue:'Lanjutkan', compose:'Apa yang sedang kamu buat?', publish:'Terbitkan', image:'Gambar', video:'Video', audio:'Audio', poll:'Jajak pendapat', discussion:'Diskusi', topic:'Topik', linkedProject:'Proyek publik' },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const stored = () => localStorage.getItem('mora-language') || localStorage.getItem('marea-language')
  const [language, setLanguage] = useState(() => stored() || 'en')
  const [hasChosen, setHasChosen] = useState(() => Boolean(stored()))
  const chooseLanguage = (next) => { if (!interfaceLanguages.some(([code]) => code === next)) return; setLanguage(next); setHasChosen(true); localStorage.setItem('mora-language', next) }
  useEffect(() => { document.documentElement.lang = language }, [language])
  const value = useMemo(() => ({ language, setLanguage: chooseLanguage, toggle: () => chooseLanguage(language === 'vi' ? 'en' : 'vi'), hasChosen, t: { ...translations.en, ...translations[language] } }), [language, hasChosen])
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() { return useContext(LanguageContext) }
